server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-db
    username: sa
    password: password

logging:
  level:
    org.springframework:
      orm.jpa: INFO
      transaction: INFO
      transaction.interceptor: DEBUG
      orm.jpa.JpaTransactionManager: DEBUG

stats-server:
  id: stats-server
